name: CI

on:
  push:
    # branches:
    #   - main
    #   - master
    #   - next
    #   - "v*"
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  setup_pnpm:
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

  test:
    needs: [setup_pnpm]
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v5
    with:
      license-check: true
      lint: true
